version: "3"

services:

  mysql56:
    image: mysql:5.6.51
    container_name: mysql56
    hostname: mysql56
    restart: always
    volumes:
      - ${WORKPATH}/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USR}

  web:
    links:
      - "mysql56"
    image: ranay4/pdfs:0.02
    container_name: servicios
    hostname: ${HOST_NAME}
    environment:
      - TZ=America/Tijuana
    ports:
      - 80:80
    volumes:
      - ${WORKPATH}/html:/opt/data
      - ${WORKPATH}/Cron:/opt/Cron

